name = "myfyp"
main = "src/entry.py"
compatibility_date = "2026-02-17"
compatibility_flags = ["python_workers"]
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "myfyp"
database_id = "00000000-0000-0000-0000-000000000000"

[triggers]
crons = ["0 * * * *"]

[vars]
ABUSE_LIMITING_ENABLED = "0"

[observability.logs]
enabled = true
